"""Long-term memory: the third state scope (Chapter 5).

drangue keeps the three kinds of state the book separates, by lifetime:

  - Task state is the durable event log. It is authoritative and is what a run
    resumes from. (store/, engine/)
  - Conversation state is a derived view of the log, regenerated by folding it,
    never stored on its own. (orchestrator.fold) That is what prevents the
    "state drift" failure where conversation and task state disagree on recovery.
  - Long-term memory persists across runs. It is different in kind: it needs an
    explicit staleness policy, because the world now is more authoritative than
    your record of the world then. Current evidence wins when they conflict.

This module is the seam only. The default is NullMemory: many production agents
need no long-term memory, and "remember everything" is mostly noise. Wiring
retrieval into the loop, scoped to specific high-value queries, comes later.
"""

from __future__ import annotations

import typing as t
from dataclasses import dataclass


@dataclass
class MemoryItem:
    key: str
    value: str
    # Staleness contract: when this fact should stop being trusted without
    # re-verification. None means it does not expire on its own.
    expires_at: float | None = None


class Memory(t.Protocol):
    async def recall(self, query: str, *, limit: int = 5) -> list[MemoryItem]: ...
    async def remember(self, item: MemoryItem) -> None: ...


class NullMemory:
    """No long-term memory. The default."""

    async def recall(self, query: str, *, limit: int = 5) -> list[MemoryItem]:
        return []

    async def remember(self, item: MemoryItem) -> None:
        return None
