"""Long-term memory: the third state scope (Chapter 5).

drangue keeps the three kinds of state the book separates, by lifetime:

  - Task state is the durable event log. It is authoritative and is what a run
    resumes from. (store/, engine/)
  - Conversation state is a derived view of the log, regenerated by folding it,
    never stored on its own. (orchestrator.fold) That is what prevents the
    "state drift" failure where conversation and task state disagree on recovery.
  - Long-term memory persists across runs. It is different in kind: it needs an
    explicit staleness policy, because the world now is more authoritative than
    your record of the world then. Current evidence wins when they conflict.

Recall is wired into the loop: when an Agent is given a memory, the engine
recalls against the run input before the first model step, records the result as
a `memory_recalled` event (so a resumed run replays it instead of re-querying),
and injects it into the model's system context. Writing is deliberate, not
automatic: call `Agent.remember(item)` when a run produces something worth
keeping. Auto-remembering every run is the "remember everything" anti-pattern the
chapter warns against. The default is NullMemory; many agents need none.

Expiry is enforced at recall time, not render time. The engine stamps a
`recalled_at` timestamp into the event and drops any item whose `expires_at` has
passed as of that recorded moment, before the event is written. That keeps the
check deterministic (a wall-clock test in rendering would make a fact appear on
the first run and vanish on resume) and means a stale fact never reaches the
prompt. A failing recall (a down vector DB) is non-fatal: the engine records an
empty `memory_recalled` and the run proceeds without memory, so an enhancement
never crashes the investigation. A Memory implementation owns its own
timeout/retry internally if it wants them.

Two deliberate simplifications: recall fires once, against the raw run input,
before the first model step (no mid-run recall yet; that would need per-recall
tracking rather than the single `recalled_done` flag), and recall is not counted
against the token budget.
"""

from __future__ import annotations

import typing as t
from dataclasses import dataclass


@dataclass
class MemoryItem:
    key: str
    value: str
    # Staleness contract: when this fact should stop being trusted without
    # re-verification. None means it does not expire on its own.
    expires_at: float | None = None


def item_to_dict(item: MemoryItem) -> dict:
    return {"key": item.key, "value": item.value, "expires_at": item.expires_at}


def live_items(items: list, now: float) -> list:
    """Drop items whose staleness window has passed as of `now`.

    Called once at recall time against a recorded timestamp, so the result is a
    fact in the log and replay stays deterministic.
    """
    return [i for i in items if i.expires_at is None or i.expires_at > now]


def render_context(items: list[dict]) -> str:
    """Render recalled items for injection into the model's system context."""
    if not items:
        return ""
    lines = "\n".join(f"- {it.get('value', '')}" for it in items)
    return ("Relevant prior context (may be stale; current evidence wins over "
            "memory):\n" + lines)


class Memory(t.Protocol):
    async def recall(self, query: str, *, limit: int = 5) -> list[MemoryItem]: ...
    async def remember(self, item: MemoryItem) -> None: ...


class NullMemory:
    """No long-term memory. The default."""

    async def recall(self, query: str, *, limit: int = 5) -> list[MemoryItem]:
        return []

    async def remember(self, item: MemoryItem) -> None:
        return None
